stages:
  - test
  - build
  - deploy

# Include the dependency scanning template provided by GitLab to automatically scan for vulnerabilities in project dependencies
include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  
# Run tests in the built-in GitLab Container Registry
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# Test stage with Coverage and JUnit reports
test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:9.0-alpine
  script:
    - echo "Running unit tests..."
    - dotnet restore ./TelemetryApi.sln  # Restore NuGet packages for solution
    - mkdir -p ./junit  # Create directory for JUnit test results
    - >
      dotnet test ./TelemetryApi.Tests/TelemetryApi.Tests.csproj -c Release 
      --logger:"junit;LogFilePath=$CI_PROJECT_DIR/junit/test-result.xml" 
      --collect:"XPlat Code Coverage" # Run tests and collect code coverage, outputting results in JUnit format for GitLab CI
    - apk add --no-cache grep # Install grep to extract coverage information from the Cobertura XML report
    - |
      COVERAGE_FILE=$(find . -name "coverage.cobertura.xml" | head -1) # Find the Cobertura XML report generated by the test run
      if [ -f "$COVERAGE_FILE" ]; then # Check if the coverage file exists
        COVERAGE=$(grep -oP 'line-rate="\K[^"]+' "$COVERAGE_FILE" | awk '{print $1*100}')
        echo "TOTAL_COVERAGE=$COVERAGE" # Extract the line coverage percentage from the Cobertura XML report and set it as a variable for GitLab CI to use in the coverage report
      else
        echo "TOTAL_COVERAGE=0" # If the coverage file is not found, set coverage to 0 to avoid errors in GitLab CI
      fi
  artifacts:
    when: always
    paths:
      - ./junit/test-result.xml
      - "**/TestResults/**/*.xml"
    reports:
      junit: ./junit/test-result.xml
      coverage_report:
        coverage_format: cobertura
        path: "**/TestResults/**/*.xml"
  coverage: '/TOTAL_COVERAGE=(\d+.\d+)/'

# Build the Docker image and push it to the registry
build_and_push_image:
  image: docker:24.0.5  # Use the Docker CLI image to build and push the image
  stage: build  
  services:
    - docker:24.0.5-dind  # Use Docker-in-Docker to allow building and pushing images
  variables:
    DOCKER_TLS_CERTDIR: "/certs"  # Set the TLS cert directory for secure communication with the Docker daemon
  before_script:
    - echo "Logging into GitLab Container Registry..."
    # Authenticate with the built-in registry using GitLab's automatic tokens
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  # Log in to the registry using GitLab CI/CD variables for authentication
  script:
    - echo "Building the Docker image..."
    - docker build -t $IMAGE_TAG .  # Build the Docker image using the Dockerfile in the current directory and tag it with the appropriate registry path
    - echo "Pushing the image to the registry..."
    - docker push $IMAGE_TAG  # Push the built image to the GitLab Container Registry using the tag defined in the variables section

# Configuration Management and Deployment to AWS
deploy_to_aws:
  stage: deploy
  image: alpine:latest  # Use a lightweight Linux image for Ansible
  before_script:
    - echo "Setting up Ansible and SSH environment..."
    - apk add --no-cache ansible openssh-client  # Install Ansible and SSH client in the runner container
    - mkdir -p ~/.ssh  # Create the hidden .ssh directory
    # Use the $ANSIBLE_PRIVATE_KEY File variable to provide the identity file for SSH
    - cp $ANSIBLE_PRIVATE_KEY ~/.ssh/id_ed25519
    - chmod 400 ~/.ssh/id_ed25519  # Restrict permissions to satisfy SSH security requirements
  script:
    - echo "Executing deployment playbook..."
    - cd ansible
    # Replace the hardcoded IP in the inventory file with the $SERVER_IP CI variable
    - sed -i "s/13.60.207.124/$SERVER_IP/g" inventory.ini
    # Run the Ansible playbook with injected secrets and SSH arguments to skip host key verification
    - >
      ansible-playbook playbook.yml 
      -e "smtp_pass=$SMTP_PASSWORD" 
      --private-key ~/.ssh/id_ed25519 
      -u ubuntu 
      --ssh-common-args='-o StrictHostKeyChecking=no'
  only:
    - main  # Only trigger deployment when changes are pushed to the main branch

# Documentation stage (Doxygen) -> Deploys to GitLab Pages
pages:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache doxygen graphviz
  script:
    - mkdir -p public
    # Generate Doxyfile
    - doxygen -g Doxyfile
    # Configuration tuning:
    - sed -i 's/^PROJECT_NAME.*/PROJECT_NAME = "Telemetry API"/' Doxyfile
    # Specify the input files and directories 
    - sed -i 's|^INPUT .*|INPUT = README.md TelemetryApi/ TelemetryApi.Tests/|' Doxyfile
    # Set the README.md as the main page of the documentation
    - sed -i 's|^USE_MDFILE_AS_MAINPAGE .*|USE_MDFILE_AS_MAINPAGE = README.md|' Doxyfile
    # Ignore the generated files and the README.Docker.md from the documentation
    - sed -i 's|^EXCLUDE .*|EXCLUDE = README.Docker.md TelemetryApi/obj/ TelemetryApi/bin/|' Doxyfile
    - sed -i 's/^RECURSIVE.*/RECURSIVE = YES/' Doxyfile
    - sed -i 's/^GENERATE_HTML.*/GENERATE_HTML = YES/' Doxyfile
    - sed -i 's|^HTML_OUTPUT .*|HTML_OUTPUT = public|' Doxyfile
    - doxygen Doxyfile
  artifacts:
    paths:
      - public
  only:
    - main