# Rate limit config.
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

# HTTP server configuration. Redirecting
server {
    listen 80;
    server_name ${DOMAIN_NAME};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server configuration. Proxying to the backend server.
server {
    listen 443 ssl;
    server_name ${DOMAIN_NAME};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem;

    location / {
        limit_req zone=api_limit burst=20 nodelay;

        proxy_pass         http://server:8080;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    
    # Stats endpoint with stricter rate limits.
    location /stats/ips {
        limit_req zone=api_limit burst=5 nodelay;
        proxy_pass http://server:8080/stats/ips;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Block external access to /metrics from the internet.
    # Prometheus scrapes internally via the Docker network (server:9091), so it remains unaffected.
    location /metrics {
        return 403;
    }
}