apiVersion: 1
groups:
    - orgId: 1
      name: eval-1m
      folder: API Alerts
      interval: 10s
      rules:
        - uid: api-404-spike-alert
          title: API 404 Errors Spike
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 120
                to: 0
              datasourceUid: Prometheus
              model:
                editorMode: builder
                expr: increase(http_requests_received_total{code="404"}[1m])
                format: time_series
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            description: In the last 1 minute there were more than 10 '404 Not Found' errors. Check the logs, the front-end might be faulty or bots are scanning the pages.
            summary: 404 Error spike - TelemetryAPI
          labels:
            severity: warning
          isPaused: false
          notification_settings:
            receiver: GmailAlerts
            group_by:
                - grafana_folder
                - alertname
            group_wait: 10s
            group_interval: 1m
            repeat_interval: 1h
